<?php

namespace App\Http\Controllers\Dashboard\Beneficiaries;

use App\Models\Users\Citizen;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Dashboard\StatsController as stat;

class StatsController extends stat
{
    protected function model()
    {
        return Citizen::class; // TODO: Change the autogenerated stub
    }
}
