<?php

namespace App\Http\Controllers\Dashboard\Workers;

use App\Models\Users\SocialWorker;
use Illuminate\Http\Request;
use App\Http\Controllers\Dashboard\StatsController as stat;

class StatsController extends stat
{
    protected function model()
    {
        return SocialWorker::class; // TODO: Change the autogenerated stub
    }
}
